### ISSUE TITLE
TypeError: Cannot read property 'getImageData' of null

### ISSUE THREAD

**Issue by CarolineBoyer** [antvis/G2Plot#1152]
When triggering a test with npm test, this error of code reading makes my test fail and this error appears :

```
TypeError: Cannot read property 'getImageData' of null

      3 | import {useIntl} from "react-intl";
      4 |
    > 5 | import { Line } from '@antv/g2plot';
        | ^
      6 | import Stat from "../../../utils/models/Stat";
      7 | import {StateFromAllReducers} from "../../../redux/store";
      8 | import {useSelector} from "react-redux";

      at isSupported (node_modules/@antv/g2plot/src/plots/word-cloud/wordcloud2.ts:119:12)
      at Object.<anonymous> (node_modules/@antv/g2plot/src/plots/word-cloud/wordcloud2.ts:134:3)
      at Object.<anonymous> (node_modules/@antv/g2plot/src/plots/word-cloud/layer.ts:10:1)
      at Object.<anonymous> (node_modules/@antv/g2plot/src/plots/word-cloud/index.ts:7:1)
      at Object.<anonymous> (node_modules/@antv/g2plot/src/plots/index.ts:22:1)
      at Object.<anonymous> (node_modules/@antv/g2plot/src/index.ts:11:1)
      at Object.<anonymous> (client/react/monitoring/Statistics/NbOfMessages.tsx:5:1)
```

Any change on how I can make my test pass ? It feels antv/g2plot is lacking a test somewhere about ctx being null or something.

**Comment by hustcc** [comment]
You need jest-canvas-mock，or jest electron.

**Comment by medoms** [comment]
Hi @hustcc could you please elaborate al little more? I am facing the described issue when running the default App.test in Create React App.

Thanks!
