### ISSUE TITLE
rollup build error

### ISSUE THREAD

**Issue by xiaoyu-tamu** [antvis/G2Plot#2356]
```
    "@antv/g2plot": "2.3.12",
    "react": "17.0.1",
    "react-dom": "17.0.1",
```

1: import { __extends } from "tslib";
2: import { VIEW_LIFE_CIRCLE, Event } from '@antv/g2';
            ^
3: import { Plot } from '../../core/plot';
4: import { adaptor, pieAnnotation } from './adaptor';
error during build:
Error: 'VIEW_LIFE_CIRCLE' is not exported by node_modules/@antv/g2/esm/index.js, imported by node_modules/@antv/g2plot/esm/plots/pie/index.js
    at error (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:5239:30)
    at Module.error (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:9950:16)
    at Module.traceVariable (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:10343:29)
    at ModuleScope.findVariable (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:8798:39)
    at FunctionScope.findVariable (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:2621:38)
    at ChildScope.findVariable (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:2621:38)
    at FunctionScope.findVariable (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:2621:38)
    at ChildScope.findVariable (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:2621:38)
    at MemberExpression.bind (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:6486:49)
    at CallExpression$1.bind (/home/dev/web/node_modules/rollup/dist/shared/rollup.js:2704:31)

**Comment by hustcc** [comment]
remove your lock file, and upgrade antv/g2 to latest.

**Comment by xiaoyu-tamu** [comment]
unfortunately, it doesn't solve the issue

**Comment by xiaoyu-tamu** [comment]
NVM, i have to manually install latest g2 instead of using the one in the g2-plot dependency
